import { ArrowLeft, Download, FileText, LoaderCircle } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { getDocument, getDocumentContentUrl } from '../services/documentService'
import type { DocumentResponse } from '../types/document'
import { formatFileSize, formatFileType } from '../utils/documentFormatters'
export function DocumentViewerPage() {
  const { id } = useParams(); const documentId = Number(id); const [document, setDocument] = useState<DocumentResponse | null>(null); const [text, setText] = useState<string | null>(null); const [error, setError] = useState<string | null>(null)
  useEffect(() => { if (!Number.isInteger(documentId)) { setError('This document could not be found.'); return }; let active = true; getDocument(documentId).then(async (result) => { if (!active) return; setDocument(result); if (result.fileType === 'text/plain') { const response = await fetch(getDocumentContentUrl(documentId)); if (!response.ok) throw new Error(); if (active) setText(await response.text()) } }).catch(() => { if (active) setError("We couldn't load this document.") }); return () => { active = false } }, [documentId])
  return <section className="mx-auto flex h-[calc(100vh-72px)] w-full max-w-7xl flex-col px-4 py-6 sm:px-6 lg:px-10"><Link to="/documents" className="inline-flex items-center gap-2 text-sm font-semibold text-orange-700 hover:text-orange-800"><ArrowLeft className="size-4" />Back to Documents</Link>{!document && !error && <div className="flex flex-1 items-center justify-center"><p className="flex items-center gap-2 text-sm text-slate-500"><LoaderCircle className="size-4 animate-spin text-orange-600" />Loading document...</p></div>}{error && <div className="mt-6 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800" role="alert">{error}</div>}{document && <><header className="mt-5 flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-orange-50 text-orange-700"><FileText className="size-5" /></span><div className="min-w-0"><h1 className="truncate text-lg font-semibold text-slate-900">{document.fileName}</h1><p className="mt-1 text-sm text-slate-500">{formatFileType(document.fileType, document.fileName)} · {formatFileSize(document.fileSize)}</p></div></div><a href={getDocumentContentUrl(documentId, true)} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50"><Download className="size-4" />Download</a></header><div className="mt-5 min-h-0 flex-1 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{document.fileType === 'application/pdf' && <iframe title={`Preview of ${document.fileName}`} src={getDocumentContentUrl(documentId)} className="h-full min-h-[32rem] w-full" />}{document.fileType === 'text/plain' && (text === null ? <div className="flex h-full items-center justify-center"><LoaderCircle className="size-5 animate-spin text-orange-600" /></div> : <pre className="h-full overflow-auto whitespace-pre-wrap p-6 font-sans text-sm leading-7 text-slate-700">{text}</pre>)}{document.fileType !== 'application/pdf' && document.fileType !== 'text/plain' && <div className="flex h-full min-h-64 flex-col items-center justify-center p-8 text-center"><FileText className="size-10 text-orange-600" /><h2 className="mt-4 text-lg font-semibold text-slate-900">Preview unavailable for DOCX</h2><p className="mt-2 max-w-md text-sm leading-6 text-slate-500">Your browser cannot safely preview this file type. Download it to open it in a compatible application.</p></div>}</div></>}</section>
}
